# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e1a47fac322854a5a4702a1c7d590921f503c8c7e78a313067db6bd789218fa449c3ce01eec235d3e1446439b5eb6fc5bec510b3251509bbccfac0611577a3a

test:
  secret_key_base: fcdd144fb20e49f153d51c1ce22f3b8c0d6b9805e513e54e2d215e7f4f637f1bfe86d2393a746b46ceacdc7e4bc10585418ceed045abed4f61766ded3dca5668

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
